### PR TITLE
Drop support for Node.js 16

### PR DESCRIPTION
**Pull request by Mrtenz**
Node.js 16 is EOL, so we can drop support for it.

### Blocking

- #220
- #219

### Blocked by

- https://github.com/MetaMask/mobile-planning/issues/1261

### CODE REVIEW

**Comment by MajorLift** [comment]
We might want to update the `engines.node` field in package.json to `>=18.0.0` as well.

**Comment by MajorLift** [comment]
Line 93-94 of `constraints.pro` also needs to be updated:
```
% The package must specify a minimum Node version of 18.
gen_enforced_field(WorkspaceCwd, 'engines.node', '>=18.0.0').
```

**Comment by mcmire** [comment]
On a surface level now that mobile is on Node 18 I agree with this. I guess this assumes that we want to go with #216, however? It seemed that the conversation about `node.engines` wasn't quite resolved (I know Mark raised one about that vs. `.nvmrc` in Slack a while back).

**Review by mcmire — DISMISSED** [review]
Marking this as blocked by discussion in https://github.com/MetaMask/metamask-module-template/pull/216 and also in Slack.

**Review by mcmire — DISMISSED** [review]

**Comment by mcmire** [comment]
I've fixed the merge conflicts on this PR. I also took the liberty to update to 18.18 (the current minor version as of this writing).

**Review by MajorLift — APPROVED** [review]
LGTM!

**Pull request merged**
